//The following is a list of defs to be used for the Torch loadout.

//For jobs that allow for decorative or ceremonial clothing
#define FORMAL_ROLES list(/datum/job/liaison, /datum/job/rd, /datum/job/submap/aaaa_head/agent/aegis, /datum/job/submap/aaaa_head/agent/leader/aegis, /datum/job/submap/aaaa_head/robot/aegis, /datum/job/submap/aegis_alt/leader, /datum/job/submap/aegis_alt/merc, /datum/job/submap/aegis_alt/merc_spec, /datum/job/submap/aegis_alt/merc_pilot, /datum/job/submap/aegis_alt/engineer, /datum/job/submap/aegis_alt/surgeon, /datum/job/senior_scientist, /decl/submap_archetype/playablecity, /datum/job/submap/citydweller, /datum/job/submap/yacht, /datum/job/submap/venera/pilot, /datum/job/submap/venera/captain, /datum/job/submap/venera/gunner, /datum/job/submap/venera/rifleman, /datum/job/submap/smuggler, /datum/job/submap/providence/trucker, /datum/job/submap/camp/psionic, /datum/job/submap/camp/teacher, /datum/job/submap/carrier_chef, /datum/job/submap/carrier_salvager, /datum/job/submap/carrier_captain, /datum/job/submap/carrier_crewman, /datum/job/submap/carrier_pilot, /datum/job/submap/carrier_doctor, /datum/job/submap/ares, /datum/job/submap/swordfish/pilot, /datum/job/submap/aegis/captain, /datum/job/submap/aegis/officer, /datum/job/submap/aegis/pilot, /datum/job/submap/aegis/gunner, /datum/job/submap/aegis/surgeon, /datum/job/submap/aegis/field_engineer, /datum/job/submap/aegis/rifleman, /datum/job/submap/aegis/field_medic,/datum/job/scientist, /datum/job/scientist_assistant, /datum/job/psychiatrist, /datum/job/representative, /datum/job/assistant, /datum/job/merchant, /datum/job/detective, /datum/job/chaplain, /datum/job/submap/bearcat_captain, /datum/job/submap/bearcat_crewman, /datum/job/submap/colonist, /datum/job/submap/pod, /datum/job/chef, /datum/job/submap/scavver_pilot, /datum/job/submap/scavver_doctor, /datum/job/submap/scavver, /datum/job/submap/scavver_engineer) /*/datum/job/research_guard*/

//For civilian jobs that may have a uniform, but not a strict one
#define SEMIFORMAL_ROLES list(/datum/job/assistant, /datum/job/cargo_tech, /datum/job/submap/aaaa_head/agent/aegis, /datum/job/submap/aaaa_head/agent/leader/aegis, /datum/job/submap/aaaa_head/robot/aegis, /datum/job/submap/aegis_alt/leader, /datum/job/submap/aegis_alt/merc, /datum/job/submap/aegis_alt/merc_spec, /datum/job/submap/aegis_alt/merc_pilot, /datum/job/submap/aegis_alt/engineer, /datum/job/submap/aegis_alt/surgeon, /datum/job/submap/citydweller, /decl/submap_archetype/playablecity, /datum/job/submap/yacht, /datum/job/submap/venera/pilot, /datum/job/submap/venera/captain, /datum/job/submap/venera/gunner, /datum/job/submap/venera/rifleman, /datum/job/submap/carrier_captain, /datum/job/submap/smuggler, /datum/job/submap/providence/trucker, /datum/job/submap/camp/teacher, /datum/job/submap/camp/psionic, /datum/job/submap/carrier_salvager, /datum/job/submap/carrier_chef, /datum/job/submap/carrier_doctor, /datum/job/submap/carrier_crewman, /datum/job/submap/carrier_pilot, /datum/job/mining, /datum/job/submap/ares, /datum/job/submap/swordfish/pilot, /datum/job/submap/aegis/captain, /datum/job/submap/aegis/officer, /datum/job/submap/aegis/pilot, /datum/job/submap/aegis/gunner, /datum/job/submap/aegis/surgeon, /datum/job/submap/aegis/field_engineer, /datum/job/submap/aegis/rifleman, /datum/job/submap/aegis/field_medic,/datum/job/scientist_assistant, /datum/job/psychiatrist, /datum/job/merchant, /datum/job/nt_pilot, /datum/job/scientist, /datum/job/senior_scientist, /datum/job/detective, /datum/job/chaplain, /datum/job/engineer, /datum/job/roboticist, /datum/job/submap/bearcat_captain, /datum/job/submap/bearcat_crewman, /datum/job/submap/colonist, /datum/job/submap/pod, /datum/job/chef, /datum/job/submap/scavver_pilot, /datum/job/submap/scavver, /datum/job/submap/scavver_doctor, /datum/job/submap/scavver_engineer, /datum/job/senior_doctor, /datum/job/junior_doctor, /datum/job/doctor) /*/datum/job/synthetic*/

//For civilian jobs that may have a strict uniform.
#define SEMIANDFORMAL_ROLES list(/datum/job/assistant, /datum/job/mining, /datum/job/submap/aaaa_head/agent/aegis, /datum/job/submap/aaaa_head/agent/leader/aegis, /datum/job/submap/aaaa_head/robot/aegis, /datum/job/submap/aegis_alt/leader, /datum/job/submap/aegis_alt/merc, /datum/job/submap/aegis_alt/merc_spec, /datum/job/submap/aegis_alt/merc_pilot, /datum/job/submap/aegis_alt/engineer, /datum/job/submap/aegis_alt/surgeon, /datum/job/submap/citydweller, /decl/submap_archetype/playablecity, /datum/job/submap/yacht, /datum/job/submap/venera/pilot, /datum/job/submap/venera/captain, /datum/job/submap/venera/gunner, /datum/job/submap/venera/rifleman, /datum/job/submap/carrier_chef, /datum/job/submap/smuggler, /datum/job/submap/providence/trucker, /datum/job/submap/camp/teacher, /datum/job/submap/camp/psionic, /datum/job/submap/carrier_salvager, /datum/job/submap/carrier_captain, /datum/job/submap/carrier_doctor, /datum/job/submap/carrier_crewman, /datum/job/submap/carrier_pilot, /datum/job/submap/aegis/rifleman, /datum/job/submap/ares, /datum/job/submap/swordfish/pilot, /datum/job/submap/aegis/captain, /datum/job/submap/aegis/officer, /datum/job/submap/aegis/pilot, /datum/job/submap/aegis/gunner, /datum/job/submap/aegis/surgeon, /datum/job/submap/aegis/field_engineer, /datum/job/submap/aegis/field_medic, /datum/job/scientist_assistant, /datum/job/psychiatrist, /datum/job/merchant, /datum/job/nt_pilot, /datum/job/liaison, /datum/job/rd, /datum/job/senior_scientist, /datum/job/scientist, /datum/job/representative, /datum/job/detective, /datum/job/chaplain, /datum/job/submap/bearcat_captain, /datum/job/submap/bearcat_crewman, /datum/job/submap/colonist, /datum/job/submap/pod, /datum/job/chef, /datum/job/submap/scavver_pilot, /datum/job/submap/scavver, /datum/job/submap/scavver_doctor, /datum/job/submap/scavver_engineer, /datum/job/senior_doctor, /datum/job/junior_doctor, /datum/job/doctor, /datum/job/research_guard) /*/datum/job/synthetic*/

//For civilian jobs with no uniform or formal clothing requirements.
#define CASUAL_ROLES list(/datum/job/assistant, /datum/job/janitor, /datum/job/chef, /datum/job/submap/aaaa_head/agent/aegis, /datum/job/submap/aaaa_head/agent/leader/aegis, /datum/job/submap/aaaa_head/robot/aegis, /datum/job/submap/aegis_alt/leader, /datum/job/submap/aegis_alt/merc, /datum/job/submap/aegis_alt/merc_spec, /datum/job/submap/aegis_alt/merc_pilot, /datum/job/submap/aegis_alt/engineer, /datum/job/submap/aegis_alt/surgeon, /datum/job/submap/yacht, /decl/submap_archetype/playablecity, /datum/job/submap/citydweller, /datum/job/cargo_tech, /datum/job/submap/venera/pilot, /datum/job/submap/venera/captain, /datum/job/submap/venera/gunner, /datum/job/submap/venera/rifleman, /datum/job/submap/smuggler, /datum/job/submap/providence/trucker, /datum/job/submap/camp/teacher, /datum/job/submap/camp/psionic, /datum/job/submap/carrier_chef, /datum/job/submap/carrier_salvager, /datum/job/submap/carrier_doctor, /datum/job/submap/carrier_crewman, /datum/job/submap/carrier_captain, /datum/job/submap/carrier_pilot, /datum/job/submap/ares, /datum/job/submap/swordfish/pilot, /datum/job/submap/aegis/captain, /datum/job/submap/aegis/officer, /datum/job/submap/aegis/pilot, /datum/job/submap/aegis/gunner, /datum/job/submap/aegis/surgeon, /datum/job/submap/aegis/field_engineer, /datum/job/submap/aegis/rifleman, /datum/job/submap/aegis/field_medic, /datum/job/roboticist, /datum/job/mining, /datum/job/chaplain, /datum/job/merchant, /datum/job/submap/bearcat_captain, /datum/job/submap/bearcat_crewman, /datum/job/submap/colonist, /datum/job/submap/pod, /datum/job/submap/scavver_pilot, /datum/job/submap/scavver_doctor, /datum/job/submap/scavver, /datum/job/submap/scavver_engineer, /datum/job/senior_doctor, /datum/job/junior_doctor, /datum/job/doctor, /datum/job/scientist, /datum/job/senior_scientist, /datum/job/scientist_assistant) /*/datum/job/synthetic*/

//For roles that would have a higher level of education, typically doctors and other scientists
#define DOCTOR_ROLES list(/datum/job/cmo, /datum/job/senior_doctor, /datum/job/junior_doctor, /datum/job/submap/aaaa_head/agent/aegis, /datum/job/submap/aaaa_head/agent/leader/aegis, /datum/job/submap/aaaa_head/robot/aegis, /datum/job/submap/aegis_alt/leader, /datum/job/submap/aegis_alt/merc, /datum/job/submap/aegis_alt/merc_spec, /datum/job/submap/aegis_alt/merc_pilot, /datum/job/submap/aegis_alt/engineer, /datum/job/submap/aegis_alt/surgeon, /datum/job/submap/citydweller, /datum/job/submap/lab_scientist, /datum/job/submap/lab_senscientist, /datum/job/submap/lab_director, /datum/job/submap/CTI_professor, /datum/job/submap/CTI_Undergraduate_Xenoscience_Researcher, /datum/job/submap/scavver_doctor, /datum/job/submap/carrier_doctor, /datum/job/submap/camp/doctor, /datum/job/submap/aegis/surgeon, /datum/job/submap/aegis/field_medic, /datum/job/submap/airfield/engineer, /datum/job/chemist, /datum/job/psychiatrist, /datum/job/roboticist, /datum/job/rd, /datum/job/senior_scientist, /datum/job/scientist) /*/datum/job/synthetic*/

//For members of the medical department
#define MEDICAL_ROLES list(/datum/job/cmo, /datum/job/senior_doctor, /datum/job/submap/camp/doctor, /datum/job/submap/aaaa_head/agent/aegis, /datum/job/submap/aaaa_head/agent/leader/aegis, /datum/job/submap/aaaa_head/robot/aegis, /datum/job/submap/aegis_alt/leader, /datum/job/submap/aegis_alt/merc, /datum/job/submap/aegis_alt/merc_spec, /datum/job/submap/aegis_alt/merc_pilot, /datum/job/submap/aegis_alt/engineer, /datum/job/submap/aegis_alt/surgeon, /datum/job/submap/citydweller,/datum/job/submap/CTI_professor, /datum/job/submap/CTI_Undergraduate_Xenoscience_Researcher, /datum/job/submap/scavver_doctor, /datum/job/submap/airfield/engineer, /datum/job/submap/aegis/surgeon, /datum/job/submap/carrier_doctor, /datum/job/submap/aegis/field_medic, /datum/job/junior_doctor, /datum/job/doctor, /datum/job/psychiatrist, /datum/job/chemist, /datum/job/medical_trainee, /datum/job/expmed) /*/datum/job/synthetic*/

//For members of the medical department, roboticists, and some Research
#define STERILE_ROLES list(/datum/job/cmo, /datum/job/senior_doctor, /datum/job/junior_doctor, /datum/job/submap/aaaa_head/agent/aegis, /datum/job/submap/aaaa_head/agent/leader/aegis, /datum/job/submap/aaaa_head/robot/aegis, /datum/job/submap/aegis_alt/leader, /datum/job/submap/aegis_alt/merc, /datum/job/submap/aegis_alt/merc_spec, /datum/job/submap/aegis_alt/merc_pilot, /datum/job/submap/aegis_alt/engineer, /datum/job/submap/aegis_alt/surgeon, /datum/job/submap/citydweller, /datum/job/submap/CTI_Undergraduate_Xenoscience_Researcher, /datum/job/submap/CTI_professor, /datum/job/submap/scavver_doctor, /datum/job/submap/camp/doctor, /datum/job/submap/airfield/engineer, /datum/job/submap/carrier_doctor, /datum/job/submap/aegis/surgeon, /datum/job/submap/aegis/field_medic, /datum/job/doctor, /datum/job/chemist, /datum/job/psychiatrist, /datum/job/roboticist, /datum/job/rd, /datum/job/senior_scientist, /datum/job/scientist, /datum/job/scientist_assistant, /datum/job/medical_trainee, /datum/job/expmed) /*/datum/job/synthetic*/

//For members of the engineering department
#define ENGINEERING_ROLES list(/datum/job/chief_engineer, /datum/job/senior_engineer, /datum/job/submap/aaaa_head/agent/aegis, /datum/job/submap/aaaa_head/agent/leader/aegis, /datum/job/submap/aaaa_head/robot/aegis, /datum/job/submap/aegis_alt/leader, /datum/job/submap/aegis_alt/merc, /datum/job/submap/aegis_alt/merc_spec, /datum/job/submap/aegis_alt/merc_pilot, /datum/job/submap/aegis_alt/engineer, /datum/job/submap/aegis_alt/surgeon, /datum/job/submap/providence/trucker, /datum/job/submap/aegis/field_engineer, /datum/job/submap/bearcat_captain, /datum/job/submap/ares, /datum/job/submap/carrier_salvager, /datum/job/submap/bearcat_crewman, /datum/job/submap/carrier_captain, /datum/job/submap/carrier_pilot, /datum/job/submap/carrier_crewman, /datum/job/submap/scavver_pilot, /datum/job/submap/scavver_doctor, /datum/job/submap/scavver, /datum/job/submap/working_beacon/overseer, /datum/job/submap/scavver_engineer, /datum/job/submap/citydweller, /datum/job/submap/colonist2, /datum/job/submap/smuggler, /datum/job/engineer, /datum/job/roboticist, /datum/job/engineer_trainee, /datum/job/expeng) /*/datum/job/synthetic*/

//For members of Engineering, Cargo, and Research
#define TECHNICAL_ROLES list(/datum/job/senior_engineer, /datum/job/engineer, /datum/job/submap/providence/trucker, /datum/job/submap/aaaa_head/agent/aegis, /datum/job/submap/aaaa_head/agent/leader/aegis, /datum/job/submap/aaaa_head/robot/aegis, /datum/job/submap/aegis_alt/leader, /datum/job/submap/aegis_alt/merc, /datum/job/submap/aegis_alt/merc_spec, /datum/job/submap/aegis_alt/merc_pilot, /datum/job/submap/aegis_alt/engineer, /datum/job/submap/aegis_alt/surgeon, /datum/job/submap/aegis/field_engineer, /datum/job/submap/bearcat_crewman, /datum/job/submap/ares, /datum/job/submap/bearcat_captain, /datum/job/submap/scavver_pilot, /datum/job/submap/carrier_salvager, /datum/job/submap/carrier_crewman, /datum/job/submap/carrier_captain, /datum/job/submap/carrier_pilot, /datum/job/submap/scavver_doctor, /datum/job/submap/scavver, /datum/job/submap/working_beacon/overseer, /datum/job/submap/scavver_engineer, /datum/job/submap/citydweller, /datum/job/submap/colonist2, /datum/job/submap/smuggler, /datum/job/roboticist, /datum/job/qm, /datum/job/cargo_tech, /datum/job/mining, /datum/job/scientist_assistant, /datum/job/merchant, /datum/job/rd, /datum/job/senior_scientist, /datum/job/scientist, /datum/job/chief_engineer, /datum/job/janitor, /datum/job/engineer_trainee, /datum/job/nt_pilot, /datum/job/expeng) /*/datum/job/synthetic*/

//For members of the security department
#define SECURITY_ROLES list(/datum/job/hos, /datum/job/warden, /datum/job/detective, /datum/job/submap/aaaa_head/agent/aegis, /datum/job/submap/aaaa_head/agent/leader/aegis, /datum/job/submap/aaaa_head/robot/aegis, /datum/job/submap/aegis_alt/leader, /datum/job/submap/aegis_alt/merc, /datum/job/submap/aegis_alt/merc_spec, /datum/job/submap/aegis_alt/merc_pilot, /datum/job/submap/aegis_alt/engineer, /datum/job/submap/aegis_alt/surgeon, /datum/job/officer, /datum/job/submap/venera/pilot, /datum/job/submap/venera/rifleman, /datum/job/submap/venera/captain, /datum/job/submap/venera/gunner, /datum/job/submap/aegis/rifleman, /datum/job/submap/aegis/pilot, /datum/job/submap/citydweller, /datum/job/submap/aegis/gunner, /datum/job/submap/aegis/officer, /datum/job/submap/aegis/captain, /datum/job/submap/airfield/command/instructor, /datum/job/submap/airfield/command/assistant) /*/datum/job/expmar*/

//For members of the supply department
#define SUPPLY_ROLES list(/datum/job/qm, /datum/job/cargo_tech, /datum/job/submap/aaaa_head/agent/aegis, /datum/job/submap/aaaa_head/agent/leader/aegis, /datum/job/submap/aaaa_head/robot/aegis, /datum/job/submap/aegis_alt/leader, /datum/job/submap/aegis_alt/merc, /datum/job/submap/aegis_alt/merc_spec, /datum/job/submap/aegis_alt/merc_pilot, /datum/job/submap/aegis_alt/engineer, /datum/job/submap/aegis_alt/surgeon, /datum/job/submap/airfield/engineer, /datum/job/submap/providence/trucker, /datum/job/submap/working_beacon/overseer, /datum/job/submap/smuggler, /datum/job/submap/citydweller, /datum/job/submap/carrier_crewman, /datum/job/submap/bearcat_captain, /datum/job/submap/carrier_salvager, /datum/job/submap/carrier_captain, /datum/job/submap/ares, /datum/job/submap/bearcat_crewman, /datum/job/submap/aegis/field_engineer)

//For members of the service department
#define SERVICE_ROLES list(/datum/job/chief_steward, /datum/job/janitor, /datum/job/submap/aaaa_head/agent/aegis, /datum/job/submap/aaaa_head/agent/leader/aegis, /datum/job/submap/aaaa_head/robot/aegis, /datum/job/submap/aegis_alt/leader, /datum/job/submap/aegis_alt/merc, /datum/job/submap/aegis_alt/merc_spec, /datum/job/submap/aegis_alt/merc_pilot, /datum/job/submap/aegis_alt/engineer, /datum/job/submap/aegis_alt/surgeon, /datum/job/chef, /datum/job/crew, /datum/job/chaplain, /datum/job/submap/airfield/engineer, /datum/job/submap/carrier_crewman, /datum/job/submap/carrier_chef, /datum/job/submap/providence/trucker, /datum/job/submap/working_beacon/overseer, /datum/job/submap/camp/cook, /datum/job/submap/yacht, /datum/job/submap/lab_cook, /datum/job/submap/citydweller, /datum/job/submap/colonist, /datum/job/submap/colonist2) /*/datum/job/synthetic*/

//For members of the exploration department
#define EXPLORATION_ROLES list(/datum/job/pathfinder, /datum/job/nt_pilot, /datum/job/submap/aaaa_head/agent/aegis, /datum/job/submap/aaaa_head/agent/leader/aegis, /datum/job/submap/aaaa_head/robot/aegis, /datum/job/submap/aegis_alt/leader, /datum/job/submap/aegis_alt/merc, /datum/job/submap/aegis_alt/merc_spec, /datum/job/submap/aegis_alt/merc_pilot, /datum/job/submap/aegis_alt/engineer, /datum/job/submap/aegis_alt/surgeon, /datum/job/explorer, /datum/job/expeng, /datum/job/expmed) /*/datum/job/synthetic*/ /*/datum/job/expmar*/

//For members of the research department and jobs that are scientific
#define RESEARCH_ROLES list(/datum/job/rd, /datum/job/scientist, /datum/job/mining, /datum/job/submap/aaaa_head/agent/aegis, /datum/job/submap/aaaa_head/agent/leader/aegis, /datum/job/submap/aaaa_head/robot/aegis, /datum/job/submap/aegis_alt/leader, /datum/job/submap/aegis_alt/merc, /datum/job/submap/aegis_alt/merc_spec, /datum/job/submap/aegis_alt/merc_pilot, /datum/job/submap/aegis_alt/engineer, /datum/job/submap/aegis_alt/surgeon, /datum/job/scientist_assistant, /datum/job/assistant, /datum/job/nt_pilot, /datum/job/senior_scientist, /datum/job/roboticist, /datum/job/submap/skrellscoutship_crew, /datum/job/submap/skrellscoutship_crew/leader, /datum/job/submap/CTI_Undergraduate_Xenoscience_Researcher, /datum/job/submap/CTI_professor, /datum/job/submap/lab_scientist, /datum/job/submap/lab_senscientist, /datum/job/submap/lab_director,/datum/job/research_guard) /*/datum/job/synthetic*/

//For jobs that spawn with weapons in their lockers
#define ARMED_ROLES list(/datum/job/captain, /datum/job/hop, /datum/job/rd, /datum/job/cmo, /datum/job/submap/aaaa_head/agent/aegis, /datum/job/submap/aaaa_head/agent/leader/aegis, /datum/job/submap/aaaa_head/robot/aegis, /datum/job/submap/aegis_alt/leader, /datum/job/submap/aegis_alt/merc, /datum/job/submap/aegis_alt/merc_spec, /datum/job/submap/aegis_alt/merc_pilot, /datum/job/submap/aegis_alt/engineer, /datum/job/submap/aegis_alt/surgeon, /datum/job/chief_engineer, /datum/job/hos, /datum/job/sea, /datum/job/officer, /datum/job/warden, /datum/job/detective, /datum/job/merchant, /datum/job/submap/scavver_pilot, /datum/job/submap/scavver_doctor, /datum/job/submap/scavver_engineer, /datum/job/submap/airfield/command/instructor, /datum/job/submap/airfield/command/assistant, /datum/job/submap/aegis/captain, /datum/job/submap/aegis/pilot, /datum/job/submap/aegis/gunner, /datum/job/submap/aegis/surgeon, /datum/job/submap/aegis/field_engineer, /datum/job/submap/aegis/field_medic, /datum/job/submap/aegis/rifleman, /datum/job/submap/swordfish/pilot, /datum/job/submap/glasburg/pilot, /datum/job/submap/glasburg/security, /datum/job/submap/glasburg/security_chief, /datum/job/submap/comet/pilot, /datum/job/submap/shikra/pilot, /datum/job/submap/saboteur/pilot, /datum/job/submap/smuggler, /datum/job/submap/venera/captain, /datum/job/submap/venera/pilot, /datum/job/submap/venera/gunner, /datum/job/submap/venera/rifleman, /datum/job/submap/citydweller, /datum/job/submap/citymayor, /datum/job/submap/providence/trucker, /datum/job/submap/carrier_captain, /datum/job/research_guard) /*/datum/job/expmar*/

//For jobs that spawn with armor in their lockers
#define ARMORED_ROLES list(/datum/job/captain, /datum/job/hop, /datum/job/rd, /datum/job/cmo, /datum/job/submap/aaaa_head/agent/aegis, /datum/job/submap/aaaa_head/agent/leader/aegis, /datum/job/submap/aaaa_head/robot/aegis, /datum/job/submap/aegis_alt/leader, /datum/job/submap/aegis_alt/merc, /datum/job/submap/aegis_alt/merc_spec, /datum/job/submap/aegis_alt/merc_pilot, /datum/job/submap/aegis_alt/engineer, /datum/job/submap/aegis_alt/surgeon, /datum/job/chief_engineer, /datum/job/hos, /datum/job/qm, /datum/job/sea, /datum/job/officer, /datum/job/warden, /datum/job/detective, /datum/job/merchant, /datum/job/submap/skrellscoutship_crew, /datum/job/submap/skrellscoutship_crew/leader, /datum/job/submap/scavver_pilot, /datum/job/submap/scavver_doctor, /datum/job/submap/scavver_engineer, /datum/job/submap/airfield/command/instructor, /datum/job/submap/airfield/command/assistant, /datum/job/submap/aegis/captain, /datum/job/submap/aegis/pilot, /datum/job/submap/aegis/gunner, /datum/job/submap/aegis/surgeon, /datum/job/submap/aegis/field_engineer, /datum/job/submap/aegis/field_medic, /datum/job/submap/aegis/rifleman, /datum/job/submap/swordfish/pilot, /datum/job/submap/glasburg/pilot, /datum/job/submap/glasburg/security, /datum/job/submap/glasburg/security_chief, /datum/job/submap/comet/pilot, /datum/job/submap/shikra/pilot, /datum/job/submap/saboteur/pilot, /datum/job/submap/smuggler, /datum/job/submap/venera/captain, /datum/job/submap/venera/pilot, /datum/job/submap/venera/gunner, /datum/job/submap/venera/rifleman, /datum/job/submap/citydweller, /datum/job/submap/citymayor, /datum/job/submap/providence/trucker, /datum/job/submap/carrier_captain, /datum/job/research_guard) /*/datum/job/expmar*/

#define UNIFORMED_BRANCHES list(/datum/mil_branch/expeditionary_corps, /datum/mil_branch/fleet, /datum/mil_branch/army)

#define CIVILIAN_BRANCHES list(/datum/mil_branch/civilian, /datum/mil_branch/solgov) /*/datum/job/synthetic*/

#define SOLGOV_BRANCHES list(/datum/mil_branch/expeditionary_corps, /datum/mil_branch/fleet, /datum/mil_branch/army, /datum/mil_branch/solgov)
