name: Cancel
on:
  push:
    branches:
      - dev

# NB: We can discover workflow IDs for this job at https://api.github.com/repos/ORG/REPO/actions/workflows
jobs:
  cancel:
    name: 'Cancel Redundant Builds'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@bb6001c4ea612bf59c3abfc4756fbceee4f870c7
        with:
          workflow_id: 3545321
          access_token: ${{ github.token }}
