name: Compile changelogs

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  CompileCL:
    runs-on: ubuntu-latest
    if: github.repository == 'Proxima-Project/Proxi-Bay12' # to prevent this running on forks
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Install depends
        run: pip install pyyaml bs4
      - name: Compile CL
        run: python tools/changelog/ss13_genchangelog.py html/changelog.html html/changelogs
      - name: Commit And Push
        run: |
          git config --global user.name "Changelogs"
          git config --global user.email "action@github.com"
          git diff --quiet --exit-code && echo "No changes found, aborting." && exit 0
          git commit -am "Automatic changelog generation"
          git push
