name: Make changelogs

on:
  push:
    branches:
    - dev

jobs:
  MakeCL:
    runs-on: ubuntu-latest
    if: github.repository == 'Proxima-Project/Proxi-Bay12' # to prevent this running on forks
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          fetch-depth: 25
      - name: Setup python and restore cache
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Install dependencies
        run: pip install ruamel.yaml PyGithub
      - name: Make CL
        id: make-cl
        run: python tools/changelog/generate_cl.py
      - name: Commit and Push Changes
        if: steps.make-cl.outputs.pr_number != '-1'
        run: |
          git config --local user.name "Changelogs"
          git config --local user.email "action@github.com"
          git add .
          git commit -m "Automatic changelog generation for PR #${{ steps.make-cl.outputs.pr_number }} [ci skip]"
          git push
